/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ide;

import uk.ac.kcl.inf.languages.tracery.ide.AbstractTraceryLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TraceryLanguageIdeModule extends AbstractTraceryLanguageIdeModule {
}
