/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.languages.tracery.TraceryLanguageRuntimeModule;
import uk.ac.kcl.inf.languages.tracery.TraceryLanguageStandaloneSetup;
import uk.ac.kcl.inf.languages.tracery.ide.TraceryLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TraceryLanguageIdeSetup extends TraceryLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    TraceryLanguageRuntimeModule _traceryLanguageRuntimeModule = new TraceryLanguageRuntimeModule();
    TraceryLanguageIdeModule _traceryLanguageIdeModule = new TraceryLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_traceryLanguageRuntimeModule, _traceryLanguageIdeModule));
  }
}
