/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.languages.tracery.ide.contentassist.antlr.internal.InternalTraceryLanguageParser;
import uk.ac.kcl.inf.languages.tracery.services.TraceryLanguageGrammarAccess;

public class TraceryLanguageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TraceryLanguageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TraceryLanguageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInternalInstructionAccess().getAlternatives(), "rule__InternalInstruction__Alternatives");
			builder.put(grammarAccess.getTraceryProgramAccess().getGroup(), "rule__TraceryProgram__Group__0");
			builder.put(grammarAccess.getInitialValueAccess().getGroup(), "rule__InitialValue__Group__0");
			builder.put(grammarAccess.getInternalInstructionAccess().getGroup_1(), "rule__InternalInstruction__Group_1__0");
			builder.put(grammarAccess.getInternalInstructionAccess().getGroup_2(), "rule__InternalInstruction__Group_2__0");
			builder.put(grammarAccess.getInternalInstructionAccess().getGroup_3(), "rule__InternalInstruction__Group_3__0");
			builder.put(grammarAccess.getInternalInstructionAccess().getGroup_4(), "rule__InternalInstruction__Group_4__0");
			builder.put(grammarAccess.getInternalInstructionAccess().getGroup_5(), "rule__InternalInstruction__Group_5__0");
			builder.put(grammarAccess.getStandardJSONStatementAccess().getGroup(), "rule__StandardJSONStatement__Group__0");
			builder.put(grammarAccess.getStartingJSONStatementAccess().getGroup(), "rule__StartingJSONStatement__Group__0");
			builder.put(grammarAccess.getStandardValueAccess().getGroup(), "rule__StandardValue__Group__0");
			builder.put(grammarAccess.getTraceryProgramAccess().getStartingInstructionAssignment_2(), "rule__TraceryProgram__StartingInstructionAssignment_2");
			builder.put(grammarAccess.getTraceryProgramAccess().getInstructionsAssignment_3(), "rule__TraceryProgram__InstructionsAssignment_3");
			builder.put(grammarAccess.getInitialJSONExpressionAccess().getVarAssignment(), "rule__InitialJSONExpression__VarAssignment");
			builder.put(grammarAccess.getInitialValueAccess().getValueAssignment_2(), "rule__InitialValue__ValueAssignment_2");
			builder.put(grammarAccess.getInternalInstructionAccess().getValueAssignment_0(), "rule__InternalInstruction__ValueAssignment_0");
			builder.put(grammarAccess.getStandardJSONStatementAccess().getInitialValuesAssignment_6(), "rule__StandardJSONStatement__InitialValuesAssignment_6");
			builder.put(grammarAccess.getStandardJSONStatementAccess().getStandardValuesAssignment_7(), "rule__StandardJSONStatement__StandardValuesAssignment_7");
			builder.put(grammarAccess.getStartingJSONStatementAccess().getInitialValuesAssignment_3(), "rule__StartingJSONStatement__InitialValuesAssignment_3");
			builder.put(grammarAccess.getStartingJSONStatementAccess().getStandardValuesAssignment_4(), "rule__StartingJSONStatement__StandardValuesAssignment_4");
			builder.put(grammarAccess.getStandardValueAccess().getValueAssignment_3(), "rule__StandardValue__ValueAssignment_3");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment(), "rule__VariableDeclaration__NameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TraceryLanguageGrammarAccess grammarAccess;

	@Override
	protected InternalTraceryLanguageParser createParser() {
		InternalTraceryLanguageParser result = new InternalTraceryLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TraceryLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TraceryLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
