/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TraceryLanguageUiModule extends AbstractTraceryLanguageUiModule {
}
