/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.kcl.inf.languages.tracery.ui.AbstractTraceryLanguageUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TraceryLanguageUiModule extends AbstractTraceryLanguageUiModule {
  public TraceryLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
