/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui.contentassist;

import uk.ac.kcl.inf.languages.tracery.ui.contentassist.AbstractTraceryLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TraceryLanguageProposalProvider extends AbstractTraceryLanguageProposalProvider {
}
