/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.validation;

import uk.ac.kcl.inf.languages.tracery.validation.AbstractTraceryLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TraceryLanguageValidator extends AbstractTraceryLanguageValidator {
}
