/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage
 * @generated
 */
public interface TraceryLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguageFactory eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tracery Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tracery Program</em>'.
   * @generated
   */
  TraceryProgram createTraceryProgram();

  /**
   * Returns a new object of class '<em>Initial JSON Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial JSON Expression</em>'.
   * @generated
   */
  InitialJSONExpression createInitialJSONExpression();

  /**
   * Returns a new object of class '<em>initial Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>initial Value</em>'.
   * @generated
   */
  initialValue createinitialValue();

  /**
   * Returns a new object of class '<em>Internal Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Internal Instruction</em>'.
   * @generated
   */
  InternalInstruction createInternalInstruction();

  /**
   * Returns a new object of class '<em>Standard JSON Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Standard JSON Statement</em>'.
   * @generated
   */
  StandardJSONStatement createStandardJSONStatement();

  /**
   * Returns a new object of class '<em>Starting JSON Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Starting JSON Statement</em>'.
   * @generated
   */
  StartingJSONStatement createStartingJSONStatement();

  /**
   * Returns a new object of class '<em>standard Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>standard Value</em>'.
   * @generated
   */
  standardValue createstandardValue();

  /**
   * Returns a new object of class '<em>Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Declaration</em>'.
   * @generated
   */
  VariableDeclaration createVariableDeclaration();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TraceryLanguagePackage getTraceryLanguagePackage();

} //TraceryLanguageFactory
