/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface TraceryLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "traceryLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/languages/tracery/TraceryLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "traceryLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguagePackage eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
   * @generated
   */
  int TRACERY_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM__INSTRUCTIONS = 0;

  /**
   * The feature id for the '<em><b>Starting Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM__STARTING_INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Tracery Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardJSONStatementImpl <em>Standard JSON Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardJSONStatementImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStandardJSONStatement()
   * @generated
   */
  int STANDARD_JSON_STATEMENT = 4;

  /**
   * The number of structural features of the '<em>Standard JSON Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDARD_JSON_STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl <em>Initial JSON Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONExpression()
   * @generated
   */
  int INITIAL_JSON_EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_EXPRESSION__VAR = STANDARD_JSON_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initial Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_EXPRESSION__INITIAL_VALUES = STANDARD_JSON_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Standard Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_EXPRESSION__STANDARD_VALUES = STANDARD_JSON_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Initial JSON Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_EXPRESSION_FEATURE_COUNT = STANDARD_JSON_STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.initialValueImpl <em>initial Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.initialValueImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getinitialValue()
   * @generated
   */
  int INITIAL_VALUE = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>initial Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionImpl <em>Internal Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalInstruction()
   * @generated
   */
  int INTERNAL_INSTRUCTION = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_INSTRUCTION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Internal Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_INSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONStatementImpl <em>Starting JSON Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONStatementImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStartingJSONStatement()
   * @generated
   */
  int STARTING_JSON_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Initial Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTING_JSON_STATEMENT__INITIAL_VALUES = 0;

  /**
   * The feature id for the '<em><b>Standard Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTING_JSON_STATEMENT__STANDARD_VALUES = 1;

  /**
   * The number of structural features of the '<em>Starting JSON Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTING_JSON_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.standardValueImpl <em>standard Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.standardValueImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getstandardValue()
   * @generated
   */
  int STANDARD_VALUE = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDARD_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>standard Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDARD_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = INTERNAL_INSTRUCTION__VALUE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = INTERNAL_INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = INTERNAL_INSTRUCTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram <em>Tracery Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tracery Program</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram
   * @generated
   */
  EClass getTraceryProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getInstructions()
   * @see #getTraceryProgram()
   * @generated
   */
  EReference getTraceryProgram_Instructions();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getStartingInstruction <em>Starting Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Starting Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getStartingInstruction()
   * @see #getTraceryProgram()
   * @generated
   */
  EReference getTraceryProgram_StartingInstruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression <em>Initial JSON Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial JSON Expression</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression
   * @generated
   */
  EClass getInitialJSONExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getVar()
   * @see #getInitialJSONExpression()
   * @generated
   */
  EReference getInitialJSONExpression_Var();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getInitialValues <em>Initial Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initial Values</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getInitialValues()
   * @see #getInitialJSONExpression()
   * @generated
   */
  EReference getInitialJSONExpression_InitialValues();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getStandardValues <em>Standard Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Standard Values</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression#getStandardValues()
   * @see #getInitialJSONExpression()
   * @generated
   */
  EReference getInitialJSONExpression_StandardValues();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.initialValue <em>initial Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>initial Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.initialValue
   * @generated
   */
  EClass getinitialValue();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.initialValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.initialValue#getValue()
   * @see #getinitialValue()
   * @generated
   */
  EReference getinitialValue_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstruction <em>Internal Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Internal Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstruction
   * @generated
   */
  EClass getInternalInstruction();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstruction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstruction#getValue()
   * @see #getInternalInstruction()
   * @generated
   */
  EAttribute getInternalInstruction_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardJSONStatement <em>Standard JSON Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Standard JSON Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardJSONStatement
   * @generated
   */
  EClass getStandardJSONStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement <em>Starting JSON Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Starting JSON Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement
   * @generated
   */
  EClass getStartingJSONStatement();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement#getInitialValues <em>Initial Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initial Values</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement#getInitialValues()
   * @see #getStartingJSONStatement()
   * @generated
   */
  EReference getStartingJSONStatement_InitialValues();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement#getStandardValues <em>Standard Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Standard Values</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONStatement#getStandardValues()
   * @see #getStartingJSONStatement()
   * @generated
   */
  EReference getStartingJSONStatement_StandardValues();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.standardValue <em>standard Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>standard Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.standardValue
   * @generated
   */
  EClass getstandardValue();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.standardValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.standardValue#getValue()
   * @see #getstandardValue()
   * @generated
   */
  EReference getstandardValue_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TraceryLanguageFactory getTraceryLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
     * @generated
     */
    EClass TRACERY_PROGRAM = eINSTANCE.getTraceryProgram();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACERY_PROGRAM__INSTRUCTIONS = eINSTANCE.getTraceryProgram_Instructions();

    /**
     * The meta object literal for the '<em><b>Starting Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACERY_PROGRAM__STARTING_INSTRUCTION = eINSTANCE.getTraceryProgram_StartingInstruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl <em>Initial JSON Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONExpression()
     * @generated
     */
    EClass INITIAL_JSON_EXPRESSION = eINSTANCE.getInitialJSONExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_JSON_EXPRESSION__VAR = eINSTANCE.getInitialJSONExpression_Var();

    /**
     * The meta object literal for the '<em><b>Initial Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_JSON_EXPRESSION__INITIAL_VALUES = eINSTANCE.getInitialJSONExpression_InitialValues();

    /**
     * The meta object literal for the '<em><b>Standard Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_JSON_EXPRESSION__STANDARD_VALUES = eINSTANCE.getInitialJSONExpression_StandardValues();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.initialValueImpl <em>initial Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.initialValueImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getinitialValue()
     * @generated
     */
    EClass INITIAL_VALUE = eINSTANCE.getinitialValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_VALUE__VALUE = eINSTANCE.getinitialValue_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionImpl <em>Internal Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalInstruction()
     * @generated
     */
    EClass INTERNAL_INSTRUCTION = eINSTANCE.getInternalInstruction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERNAL_INSTRUCTION__VALUE = eINSTANCE.getInternalInstruction_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardJSONStatementImpl <em>Standard JSON Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardJSONStatementImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStandardJSONStatement()
     * @generated
     */
    EClass STANDARD_JSON_STATEMENT = eINSTANCE.getStandardJSONStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONStatementImpl <em>Starting JSON Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONStatementImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStartingJSONStatement()
     * @generated
     */
    EClass STARTING_JSON_STATEMENT = eINSTANCE.getStartingJSONStatement();

    /**
     * The meta object literal for the '<em><b>Initial Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STARTING_JSON_STATEMENT__INITIAL_VALUES = eINSTANCE.getStartingJSONStatement_InitialValues();

    /**
     * The meta object literal for the '<em><b>Standard Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STARTING_JSON_STATEMENT__STANDARD_VALUES = eINSTANCE.getStartingJSONStatement_StandardValues();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.standardValueImpl <em>standard Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.standardValueImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getstandardValue()
     * @generated
     */
    EClass STANDARD_VALUE = eINSTANCE.getstandardValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STANDARD_VALUE__VALUE = eINSTANCE.getstandardValue_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

  }

} //TraceryLanguagePackage
