/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface TraceryLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "traceryLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/languages/tracery/TraceryLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "traceryLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguagePackage eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
   * @generated
   */
  int TRACERY_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Tracery Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONStatementsImpl <em>First JSON Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONStatementsImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFirstJSONStatements()
   * @generated
   */
  int FIRST_JSON_STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRST_JSON_STATEMENTS__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRST_JSON_STATEMENTS__VALUE = 1;

  /**
   * The number of structural features of the '<em>First JSON Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRST_JSON_STATEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONFinishImpl <em>First JSON Finish</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONFinishImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFirstJSONFinish()
   * @generated
   */
  int FIRST_JSON_FINISH = 2;

  /**
   * The number of structural features of the '<em>First JSON Finish</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIRST_JSON_FINISH_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalValsImpl <em>Internal Vals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalValsImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalVals()
   * @generated
   */
  int INTERNAL_VALS = 6;

  /**
   * The number of structural features of the '<em>Internal Vals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_VALS_FEATURE_COUNT = FIRST_JSON_FINISH_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl <em>Initial Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialVal()
   * @generated
   */
  int INITIAL_VAL = 3;

  /**
   * The feature id for the '<em><b>Val Internal Instruction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_VAL__VAL_INTERNAL_INSTRUCTION = INTERNAL_VALS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_VAL__VALS = INTERNAL_VALS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Initial Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_VAL_FEATURE_COUNT = INTERNAL_VALS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InstructionImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 4;

  /**
   * The feature id for the '<em><b>First Instruction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__FIRST_INSTRUCTION = 0;

  /**
   * The feature id for the '<em><b>Last Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__LAST_INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionsImpl <em>Internal Instructions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionsImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalInstructions()
   * @generated
   */
  int INTERNAL_INSTRUCTIONS = 5;

  /**
   * The number of structural features of the '<em>Internal Instructions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_INSTRUCTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONFinishImpl <em>Last JSON Finish</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONFinishImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getLastJSONFinish()
   * @generated
   */
  int LAST_JSON_FINISH = 7;

  /**
   * The number of structural features of the '<em>Last JSON Finish</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_JSON_FINISH_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONStatementImpl <em>Last JSON Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONStatementImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getLastJSONStatement()
   * @generated
   */
  int LAST_JSON_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_JSON_STATEMENT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Last JSON Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAST_JSON_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardValImpl <em>Standard Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardValImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStandardVal()
   * @generated
   */
  int STANDARD_VAL = 9;

  /**
   * The feature id for the '<em><b>Val Internal Instruction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDARD_VAL__VAL_INTERNAL_INSTRUCTION = 0;

  /**
   * The number of structural features of the '<em>Standard Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDARD_VAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl <em>String Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStringDeclaration()
   * @generated
   */
  int STRING_DECLARATION = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DECLARATION__VALUE = INTERNAL_INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DECLARATION_FEATURE_COUNT = INTERNAL_INSTRUCTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 11;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VARIABLE = INTERNAL_INSTRUCTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = INTERNAL_INSTRUCTIONS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram <em>Tracery Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tracery Program</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram
   * @generated
   */
  EClass getTraceryProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getInstructions()
   * @see #getTraceryProgram()
   * @generated
   */
  EReference getTraceryProgram_Instructions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements <em>First JSON Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>First JSON Statements</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements
   * @generated
   */
  EClass getFirstJSONStatements();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements#getName()
   * @see #getFirstJSONStatements()
   * @generated
   */
  EAttribute getFirstJSONStatements_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONStatements#getValue()
   * @see #getFirstJSONStatements()
   * @generated
   */
  EReference getFirstJSONStatements_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONFinish <em>First JSON Finish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>First JSON Finish</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FirstJSONFinish
   * @generated
   */
  EClass getFirstJSONFinish();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal <em>Initial Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial Val</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal
   * @generated
   */
  EClass getInitialVal();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal#getValInternalInstruction <em>Val Internal Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Val Internal Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal#getValInternalInstruction()
   * @see #getInitialVal()
   * @generated
   */
  EReference getInitialVal_ValInternalInstruction();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal#getVals <em>Vals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vals</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal#getVals()
   * @see #getInitialVal()
   * @generated
   */
  EReference getInitialVal_Vals();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction#getFirstInstruction <em>First Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>First Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction#getFirstInstruction()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_FirstInstruction();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction#getLastInstruction <em>Last Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Last Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Instruction#getLastInstruction()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_LastInstruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstructions <em>Internal Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Internal Instructions</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstructions
   * @generated
   */
  EClass getInternalInstructions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalVals <em>Internal Vals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Internal Vals</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalVals
   * @generated
   */
  EClass getInternalVals();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONFinish <em>Last JSON Finish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Last JSON Finish</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONFinish
   * @generated
   */
  EClass getLastJSONFinish();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONStatement <em>Last JSON Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Last JSON Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONStatement
   * @generated
   */
  EClass getLastJSONStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.LastJSONStatement#getValue()
   * @see #getLastJSONStatement()
   * @generated
   */
  EReference getLastJSONStatement_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardVal <em>Standard Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Standard Val</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardVal
   * @generated
   */
  EClass getStandardVal();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardVal#getValInternalInstruction <em>Val Internal Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Val Internal Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardVal#getValInternalInstruction()
   * @see #getStandardVal()
   * @generated
   */
  EReference getStandardVal_ValInternalInstruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration <em>String Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration
   * @generated
   */
  EClass getStringDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration#getValue()
   * @see #getStringDeclaration()
   * @generated
   */
  EAttribute getStringDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration#getVariable()
   * @see #getVariableDeclaration()
   * @generated
   */
  EReference getVariableDeclaration_Variable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TraceryLanguageFactory getTraceryLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
     * @generated
     */
    EClass TRACERY_PROGRAM = eINSTANCE.getTraceryProgram();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACERY_PROGRAM__INSTRUCTIONS = eINSTANCE.getTraceryProgram_Instructions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONStatementsImpl <em>First JSON Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONStatementsImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFirstJSONStatements()
     * @generated
     */
    EClass FIRST_JSON_STATEMENTS = eINSTANCE.getFirstJSONStatements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIRST_JSON_STATEMENTS__NAME = eINSTANCE.getFirstJSONStatements_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIRST_JSON_STATEMENTS__VALUE = eINSTANCE.getFirstJSONStatements_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONFinishImpl <em>First JSON Finish</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FirstJSONFinishImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFirstJSONFinish()
     * @generated
     */
    EClass FIRST_JSON_FINISH = eINSTANCE.getFirstJSONFinish();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl <em>Initial Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialVal()
     * @generated
     */
    EClass INITIAL_VAL = eINSTANCE.getInitialVal();

    /**
     * The meta object literal for the '<em><b>Val Internal Instruction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_VAL__VAL_INTERNAL_INSTRUCTION = eINSTANCE.getInitialVal_ValInternalInstruction();

    /**
     * The meta object literal for the '<em><b>Vals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_VAL__VALS = eINSTANCE.getInitialVal_Vals();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InstructionImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>First Instruction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__FIRST_INSTRUCTION = eINSTANCE.getInstruction_FirstInstruction();

    /**
     * The meta object literal for the '<em><b>Last Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__LAST_INSTRUCTION = eINSTANCE.getInstruction_LastInstruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionsImpl <em>Internal Instructions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalInstructionsImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalInstructions()
     * @generated
     */
    EClass INTERNAL_INSTRUCTIONS = eINSTANCE.getInternalInstructions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalValsImpl <em>Internal Vals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InternalValsImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInternalVals()
     * @generated
     */
    EClass INTERNAL_VALS = eINSTANCE.getInternalVals();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONFinishImpl <em>Last JSON Finish</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONFinishImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getLastJSONFinish()
     * @generated
     */
    EClass LAST_JSON_FINISH = eINSTANCE.getLastJSONFinish();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONStatementImpl <em>Last JSON Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.LastJSONStatementImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getLastJSONStatement()
     * @generated
     */
    EClass LAST_JSON_STATEMENT = eINSTANCE.getLastJSONStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAST_JSON_STATEMENT__VALUE = eINSTANCE.getLastJSONStatement_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardValImpl <em>Standard Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StandardValImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStandardVal()
     * @generated
     */
    EClass STANDARD_VAL = eINSTANCE.getStandardVal();

    /**
     * The meta object literal for the '<em><b>Val Internal Instruction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STANDARD_VAL__VAL_INTERNAL_INSTRUCTION = eINSTANCE.getStandardVal_ValInternalInstruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl <em>String Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStringDeclaration()
     * @generated
     */
    EClass STRING_DECLARATION = eINSTANCE.getStringDeclaration();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_DECLARATION__VALUE = eINSTANCE.getStringDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLARATION__VARIABLE = eINSTANCE.getVariableDeclaration_Variable();

  }

} //TraceryLanguagePackage
