/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONExpression;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDeclaration;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.initialValue;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.standardValue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial JSON Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl#getVar <em>Var</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl#getInitialValues <em>Initial Values</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONExpressionImpl#getStandardValues <em>Standard Values</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitialJSONExpressionImpl extends StandardJSONStatementImpl implements InitialJSONExpression
{
  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected VariableDeclaration var;

  /**
   * The cached value of the '{@link #getInitialValues() <em>Initial Values</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialValues()
   * @generated
   * @ordered
   */
  protected EList<initialValue> initialValues;

  /**
   * The cached value of the '{@link #getStandardValues() <em>Standard Values</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStandardValues()
   * @generated
   * @ordered
   */
  protected EList<standardValue> standardValues;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitialJSONExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TraceryLanguagePackage.Literals.INITIAL_JSON_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration getVar()
  {
    if (var != null && var.eIsProxy())
    {
      InternalEObject oldVar = (InternalEObject)var;
      var = (VariableDeclaration)eResolveProxy(oldVar);
      if (var != oldVar)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR, oldVar, var));
      }
    }
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VariableDeclaration basicGetVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(VariableDeclaration newVar)
  {
    VariableDeclaration oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<initialValue> getInitialValues()
  {
    if (initialValues == null)
    {
      initialValues = new EObjectContainmentEList<initialValue>(initialValue.class, this, TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES);
    }
    return initialValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<standardValue> getStandardValues()
  {
    if (standardValues == null)
    {
      standardValues = new EObjectContainmentEList<standardValue>(standardValue.class, this, TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES);
    }
    return standardValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES:
        return ((InternalEList<?>)getInitialValues()).basicRemove(otherEnd, msgs);
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES:
        return ((InternalEList<?>)getStandardValues()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR:
        if (resolve) return getVar();
        return basicGetVar();
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES:
        return getInitialValues();
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES:
        return getStandardValues();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR:
        setVar((VariableDeclaration)newValue);
        return;
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES:
        getInitialValues().clear();
        getInitialValues().addAll((Collection<? extends initialValue>)newValue);
        return;
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES:
        getStandardValues().clear();
        getStandardValues().addAll((Collection<? extends standardValue>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR:
        setVar((VariableDeclaration)null);
        return;
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES:
        getInitialValues().clear();
        return;
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES:
        getStandardValues().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__VAR:
        return var != null;
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__INITIAL_VALUES:
        return initialValues != null && !initialValues.isEmpty();
      case TraceryLanguagePackage.INITIAL_JSON_EXPRESSION__STANDARD_VALUES:
        return standardValues != null && !standardValues.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InitialJSONExpressionImpl
