/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialVal;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InternalInstructions;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.StandardVal;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial Val</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl#getValInternalInstruction <em>Val Internal Instruction</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialValImpl#getVals <em>Vals</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitialValImpl extends InternalValsImpl implements InitialVal
{
  /**
   * The cached value of the '{@link #getValInternalInstruction() <em>Val Internal Instruction</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValInternalInstruction()
   * @generated
   * @ordered
   */
  protected EList<InternalInstructions> valInternalInstruction;

  /**
   * The cached value of the '{@link #getVals() <em>Vals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVals()
   * @generated
   * @ordered
   */
  protected EList<StandardVal> vals;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitialValImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TraceryLanguagePackage.Literals.INITIAL_VAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InternalInstructions> getValInternalInstruction()
  {
    if (valInternalInstruction == null)
    {
      valInternalInstruction = new EObjectContainmentEList<InternalInstructions>(InternalInstructions.class, this, TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION);
    }
    return valInternalInstruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StandardVal> getVals()
  {
    if (vals == null)
    {
      vals = new EObjectContainmentEList<StandardVal>(StandardVal.class, this, TraceryLanguagePackage.INITIAL_VAL__VALS);
    }
    return vals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION:
        return ((InternalEList<?>)getValInternalInstruction()).basicRemove(otherEnd, msgs);
      case TraceryLanguagePackage.INITIAL_VAL__VALS:
        return ((InternalEList<?>)getVals()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION:
        return getValInternalInstruction();
      case TraceryLanguagePackage.INITIAL_VAL__VALS:
        return getVals();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION:
        getValInternalInstruction().clear();
        getValInternalInstruction().addAll((Collection<? extends InternalInstructions>)newValue);
        return;
      case TraceryLanguagePackage.INITIAL_VAL__VALS:
        getVals().clear();
        getVals().addAll((Collection<? extends StandardVal>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION:
        getValInternalInstruction().clear();
        return;
      case TraceryLanguagePackage.INITIAL_VAL__VALS:
        getVals().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.INITIAL_VAL__VAL_INTERNAL_INSTRUCTION:
        return valInternalInstruction != null && !valInternalInstruction.isEmpty();
      case TraceryLanguagePackage.INITIAL_VAL__VALS:
        return vals != null && !vals.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InitialValImpl
