/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TraceryLanguageStandaloneSetup extends TraceryLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new TraceryLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
